# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2547, 1420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1990, -20, 20, 1491))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(59, 39, 1891, 971))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_switch_view = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_switch_view.setGeometry(QtCore.QRect(10, 40, 51, 211))
        self.pushButton_switch_view.setObjectName("pushButton_switch_view")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1950, 40, 16, 971))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(2150, 50, 371, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider_resolution_v = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_resolution_v.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_resolution_v.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_resolution_v.setTickInterval(5)
        self.horizontalSlider_resolution_v.setObjectName("horizontalSlider_resolution_v")
        self.verticalLayout.addWidget(self.horizontalSlider_resolution_v)
        self.horizontalSlider_resolution_h = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_resolution_h.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_resolution_h.setObjectName("horizontalSlider_resolution_h")
        self.verticalLayout.addWidget(self.horizontalSlider_resolution_h)
        self.horizontalSlider_height = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_height.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_height.setObjectName("horizontalSlider_height")
        self.verticalLayout.addWidget(self.horizontalSlider_height)
        self.horizontalSlider_bluriness = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_bluriness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_bluriness.setObjectName("horizontalSlider_bluriness")
        self.verticalLayout.addWidget(self.horizontalSlider_bluriness)
        self.horizontalSlider_obstruction = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_obstruction.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_obstruction.setObjectName("horizontalSlider_obstruction")
        self.verticalLayout.addWidget(self.horizontalSlider_obstruction)
        self.horizontalSlider_windows = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_windows.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_windows.setObjectName("horizontalSlider_windows")
        self.verticalLayout.addWidget(self.horizontalSlider_windows)
        self.horizontalSlider_windows_floor = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_windows_floor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_windows_floor.setObjectName("horizontalSlider_windows_floor")
        self.verticalLayout.addWidget(self.horizontalSlider_windows_floor)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(2059, 939, 431, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_facade = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_facade.setObjectName("radioButton_facade")
        self.horizontalLayout.addWidget(self.radioButton_facade)
        self.radioButton_window = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_window.setObjectName("radioButton_window")
        self.horizontalLayout.addWidget(self.radioButton_window)
        self.radioButton_city = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_city.setObjectName("radioButton_city")
        self.horizontalLayout.addWidget(self.radioButton_city)
        self.toolButton_load_image = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_load_image.setGeometry(QtCore.QRect(2060, 1090, 431, 61))
        self.toolButton_load_image.setObjectName("toolButton_load_image")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(2060, 1020, 431, 70))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1980, 50, 174, 757))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_resolution_v = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resolution_v.sizePolicy().hasHeightForWidth())
        self.label_resolution_v.setSizePolicy(sizePolicy)
        self.label_resolution_v.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resolution_v.setObjectName("label_resolution_v")
        self.verticalLayout_2.addWidget(self.label_resolution_v)
        self.label_resolution_h = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resolution_h.sizePolicy().hasHeightForWidth())
        self.label_resolution_h.setSizePolicy(sizePolicy)
        self.label_resolution_h.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resolution_h.setObjectName("label_resolution_h")
        self.verticalLayout_2.addWidget(self.label_resolution_h)
        self.label_height = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_height.sizePolicy().hasHeightForWidth())
        self.label_height.setSizePolicy(sizePolicy)
        self.label_height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_height.setObjectName("label_height")
        self.verticalLayout_2.addWidget(self.label_height)
        self.label_bluriness = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bluriness.sizePolicy().hasHeightForWidth())
        self.label_bluriness.setSizePolicy(sizePolicy)
        self.label_bluriness.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_bluriness.setObjectName("label_bluriness")
        self.verticalLayout_2.addWidget(self.label_bluriness)
        self.label_obstruction = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_obstruction.sizePolicy().hasHeightForWidth())
        self.label_obstruction.setSizePolicy(sizePolicy)
        self.label_obstruction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_obstruction.setObjectName("label_obstruction")
        self.verticalLayout_2.addWidget(self.label_obstruction)
        self.label_windows = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_windows.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_windows.sizePolicy().hasHeightForWidth())
        self.label_windows.setSizePolicy(sizePolicy)
        self.label_windows.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_windows.setObjectName("label_windows")
        self.verticalLayout_2.addWidget(self.label_windows)
        self.label_floors = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_floors.sizePolicy().hasHeightForWidth())
        self.label_floors.setSizePolicy(sizePolicy)
        self.label_floors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_floors.setObjectName("label_floors")
        self.verticalLayout_2.addWidget(self.label_floors)
        self.label_image_frame = QtWidgets.QLabel(self.centralwidget)
        self.label_image_frame.setGeometry(QtCore.QRect(970, 1030, 171, 23))
        self.label_image_frame.setObjectName("label_image_frame")
        self.line.raise_()
        self.pushButton_switch_view.raise_()
        self.verticalScrollBar.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.toolButton_load_image.raise_()
        self.textEdit.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.frame.raise_()
        self.label_image_frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2547, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_switch_view.setText(_translate("MainWindow", "Cluster View"))
        self.radioButton_facade.setText(_translate("MainWindow", "Facade"))
        self.radioButton_window.setText(_translate("MainWindow", "Window"))
        self.radioButton_city.setText(_translate("MainWindow", "City"))
        self.toolButton_load_image.setText(_translate("MainWindow", "..."))
        self.label_resolution_v.setText(_translate("MainWindow", "Resolution V"))
        self.label_resolution_h.setText(_translate("MainWindow", "Resolution H"))
        self.label_height.setText(_translate("MainWindow", "Height"))
        self.label_bluriness.setText(_translate("MainWindow", "Bluriness"))
        self.label_obstruction.setText(_translate("MainWindow", "Obstructions"))
        self.label_windows.setText(_translate("MainWindow", "#Windows"))
        self.label_floors.setText(_translate("MainWindow", "#Floors"))
        self.label_image_frame.setText(_translate("MainWindow", "Image Viewer"))

