# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'min_max_slider.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 113)
        Form.setMouseTracking(True)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 730, 110))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 50))
        self.label.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignJustify)
        self.label.setObjectName("label")
        self.horizontalLayout_24.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.min_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_label.sizePolicy().hasHeightForWidth())
        self.min_label.setSizePolicy(sizePolicy)
        self.min_label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.min_label.setFont(font)
        self.min_label.setAlignment(QtCore.Qt.AlignJustify)
        self.min_label.setObjectName("min_label")
        self.horizontalLayout_25.addWidget(self.min_label)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.min_text = QtWidgets.QTextBrowser(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_text.sizePolicy().hasHeightForWidth())
        self.min_text.setSizePolicy(sizePolicy)
        self.min_text.setMinimumSize(QtCore.QSize(50, 50))
        self.min_text.setMaximumSize(QtCore.QSize(50, 50))
        self.min_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.min_text.setAlignment(QtCore.Qt.AlignCenter)
        self.min_text.setObjectName("min_text")
        self.horizontalLayout_26.addWidget(self.min_text)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24.addLayout(self.verticalLayout_11)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.min_slider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_slider.sizePolicy().hasHeightForWidth())
        self.min_slider.setSizePolicy(sizePolicy)
        self.min_slider.setMinimumSize(QtCore.QSize(300, 50))
        self.min_slider.setMaximumSize(QtCore.QSize(500, 50))
        self.min_slider.setMouseTracking(True)
        self.min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.min_slider.setTickInterval(5)
        self.min_slider.setObjectName("min_slider")
        self.verticalLayout.addWidget(self.min_slider)
        self.max_slider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_slider.sizePolicy().hasHeightForWidth())
        self.max_slider.setSizePolicy(sizePolicy)
        self.max_slider.setMinimumSize(QtCore.QSize(300, 50))
        self.max_slider.setMaximumSize(QtCore.QSize(500, 50))
        self.max_slider.setMouseTracking(True)
        self.max_slider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.max_slider.setMaximum(100)
        self.max_slider.setSliderPosition(100)
        self.max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_slider.setInvertedControls(False)
        self.max_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.max_slider.setTickInterval(5)
        self.max_slider.setObjectName("max_slider")
        self.verticalLayout.addWidget(self.max_slider)
        self.horizontalLayout_24.addLayout(self.verticalLayout)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.max_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_label.sizePolicy().hasHeightForWidth())
        self.max_label.setSizePolicy(sizePolicy)
        self.max_label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.max_label.setFont(font)
        self.max_label.setAlignment(QtCore.Qt.AlignJustify)
        self.max_label.setObjectName("max_label")
        self.horizontalLayout_27.addWidget(self.max_label)
        self.verticalLayout_12.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.max_text = QtWidgets.QTextBrowser(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_text.sizePolicy().hasHeightForWidth())
        self.max_text.setSizePolicy(sizePolicy)
        self.max_text.setMinimumSize(QtCore.QSize(50, 50))
        self.max_text.setMaximumSize(QtCore.QSize(50, 50))
        self.max_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.max_text.setAlignment(QtCore.Qt.AlignJustify)
        self.max_text.setObjectName("max_text")
        self.horizontalLayout_28.addWidget(self.max_text, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_12.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_24.addLayout(self.verticalLayout_12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Label"))
        self.min_label.setText(_translate("Form", "Min"))
        self.max_label.setText(_translate("Form", "Max"))

